### ISSUE TITLE
How can I set background color of each word ?

### ISSUE THREAD

**Issue by delwar2016** [timdream/wordcloud2.js#79]
How can i set background color of each word or any way to set background color using callback as like as we are able to set front color ?

Thanks.

**Comment by timdream** [comment]
"Background" of each word does not really make sense in the construct of the word cloud because any space outside of the non-enclosing area of the glyph are available to other words, in theory. Internally the script use a grid to track such information, but I don't think you want to paint that grid behind the words.

This feature cannot be implemented because it can't be defined.

**Comment by delwar2016** [comment]
<img width="552" alt="screen shot 2016-10-24 at 8 00 28 pm" src="https://cloud.githubusercontent.com/assets/18276801/19648642/988ae06e-9a24-11e6-8e63-846c6c3ea812.png">

Please see the image , each word has a background color depending on frequency. Actually, i want to do this. is it possible then how? 

Thanks
