### ISSUE TITLE
square should not alias to diamond

### ISSUE THREAD

**Issue by ghost** [timdream/wordcloud2.js#80]
The Square shape is rotated45 degrees so it appears to be a diamond.  What if all I want was a shape equal to the canvas (square or rectangle)?   The words would be placed into the entire space available by the canvas size.  Basically the same as your Love demo.

**Comment by timdream** [comment]
You are correct on the `square` keyword – I made a mistake to alias it to `diamond`. That said, it's shouldn't be hard to work out a polar equation to draw a real square shape.

The Love demo doesn't specify any shape so it simply draw the cloud in circles. It fill up the space because I did clever things on the list and the size calculation to make sure it indeed fills up the canvas.
